distribution_sites:
  - name: Aquinas Center
    max: 100
    zips:
      - '19145'
      - '19146'
      - '19147'
      - '19148'
  - name: City Light Church
    max: 200
    zips:
      - '19127'
      - '19128'
      - '19129'
  - name: First Christian Assembly
    max: 250
    zips:
      - '19145'
      - '19146'
      - '19147'
      - '19148'
  - name: Grace and Peace
    max: 100
    zips:
      - '19120'
      - '19122'
      - '19124'
      - '19125'
      - '19124'
      - '19133'
      - '19134'
      - '19140'
      - '19141'
  - name: Liberti Collingswood
    max: 50
    zips:
      - '08108'
      - '08107'
  - name: Liberti East
    max: 350
    zips:
      - '19122'
      - '19123'
      - '19125'
      - '19133'
      - '19134'
  - name: Liberti Fairmount
    max: 300
    zips:
      - '19121'
      - '19130'
      - '19132'
  - name: Liberti Harrisburg
    max: 200
    zips:
      - '17043'
      - '17070'
