# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Request = apps.get_model('api', 'Request')
    DistributionSite = apps.get_model('api', 'DistributionSite')
    Event = apps.get_model('api', 'Event')
    EventDistributionSiteDetails = apps.get_model('api', 'EventDistributionSiteDetails')
    db_alias = schema_editor.connection.alias

    dist_site_names = Request.objects.using(db_alias).values_list('distribution_site', flat=True).distinct()
    event = Event.objects.using(db_alias).create(name='Initial Event', active=False)

    for name in dist_site_names:
        dist_site = DistributionSite.objects.create(name=name)
        details = EventDistributionSiteDetails.objects.using(db_alias).create(distribution_site=dist_site, event=event)
        Request.objects.filter(distribution_site__iexact=name).update(event_distribution_site_details=details)


def reverse(apps, schema_editor):
    # forwards() creates two Country instances,
    # so reverse() should delete them.
    DistributionSite = apps.get_model('api', 'DistributionSite')
    Event = apps.get_model('api', 'Event')
    EventDistributionSiteDetails = apps.get_model('api', 'EventDistributionSiteDetails')
    db_alias = schema_editor.connection.alias

    DistributionSite.objects.using(db_alias).all().delete()
    Event.objects.using(db_alias).all().delete()
    EventDistributionSiteDetails.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_site_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='Request',
            name='event_distribution_site_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EventDistributionSiteDetails', null=True),
        ),
        migrations.RunPython(forwards, reverse),
    ]
