# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 16:47
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Request = apps.get_model('api', 'Request')
    DistributionSite = apps.get_model('api', 'DistributionSite')
    db_alias = schema_editor.connection.alias
    dist_site_names = Request.objects.using(db_alias).values_list('distribution_site', flat=True).distinct()

    for name in dist_site_names:
        DistributionSite.objects.create(name=name)


def reverse(apps, schema_editor):
    # forwards() creates two Country instances,
    # so reverse() should delete them.
    DistributionSite = apps.get_model('api', 'DistributionSite')
    db_alias = schema_editor.connection.alias
    DistributionSite.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_site_events'),
    ]

    operations = [
      migrations.RunPython(forwards, reverse),
    ]
