# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_migrate_dist_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='phone_type',
            field=models.CharField(blank=True, choices=[(b'Home', b'Home'), (b'Mobile', b'Mobile')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone_type2',
            field=models.CharField(blank=True, choices=[(b'Home', b'Home'), (b'Mobile', b'Mobile')], max_length=20, null=True),
        ),
    ]
