# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_phone_type_enum'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionsite',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='distributionsite',
            name='apt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='distributionsite',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='distributionsite',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='distributionsite',
            name='zip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
