# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_add_site_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionsite',
            name='users',
        ),
        migrations.AddField(
            model_name='eventdistributionsitedetails',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
