# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_users_to_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributionsite',
            options={'verbose_name': 'Distribution Site', 'verbose_name_plural': 'Distribution Sites'},
        ),
        migrations.AlterModelOptions(
            name='eventdistributionsitedetails',
            options={'verbose_name': 'Event Distribution Site Details', 'verbose_name_plural': 'Event Distribution Site Details'},
        ),
    ]
