# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add-zips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdistributionsitedetails',
            name='distribution_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.DistributionSite'),
        ),
        migrations.AlterField(
            model_name='eventdistributionsitedetails',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Event'),
        ),
        migrations.AlterField(
            model_name='request',
            name='event_distribution_site_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.EventDistributionSiteDetails'),
        ),
    ]
